trigger:
- master

pool:
  vmImage: 'macOS-10.13'

jobs:
  - job: Android
    steps:
    - task: FlutterInstall@0
    - script: |
        $(FlutterToolPath)/flutter pub global activate pubspec_verion
      displayName: Install pubver tool.
  
