variables:
  projectDirectory: jama

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

jobs:
  - job: Android
    steps:
    - task: FlutterInstall@0
    - script: |
        echo $(FlutterToolPath)
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin:$(FlutterToolPath)/../.pub-cache/bin/
        echo $PATH
        flutter pub global activate pubspec_version
        pubver bump build
      displayName: Install pubver tool.
    - script: |
        git config --global user.email "tk@hinterlandsupply.co"
        git config --global user.name "Azure DevOps CI"
        git add pubspec.yaml
        git commit -m "Updated Automated Build Number [skip ci]"
        git pull origin master --rebase
        git push https://$USERNAME:$PASSWORD@github.com/hinterlandsupplyco/JaMa.git master
      displayName: Push Changes.
  
