trigger:
- master

pool:
  vmImage: 'macOS-10.13'

jobs:
  - job: Android
    steps:
    - task: FlutterInstall@0
    - script: |
        echo $(FlutterToolPath)
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)cache/dart-sdk/bin
        echo $PATH
        flutter pub global activate pubspec_version
        cd $(FlutterToolPath)../.pub-cache/bin/
        pubver bump build
      displayName: Install pubver tool.
  
