trigger:
- master

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Build_And_Test_JaMa
    steps:
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'Hsco_cert.p12'
        certPwd: '$(privateKeyPassword)'
      displayName: Installing iOS Dev Certificate
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'HSCO.mobileprovision'
      displayName: Installing iOS Dev Mobile Provisioning Profile
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'HSCO-Distribution.p12'
        certPwd: '$(privateKeyPassword)'
      displayName: Installing iOS Dist Certificate
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'HSCOjamadistribution.mobileprovision'
      displayName: Installing iOS Dist Mobile Provisioning Profile
    - task: FlutterInstall@0
    - script: |
        echo $(FlutterToolPath)
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin:$(FlutterToolPath)/../.pub-cache/bin/
        echo $PATH
        flutter pub global activate pubspec_version
        pubver bump build
        echo $(Agent.BuildDirectory)
        cd $(Agent.BuildDirectory)
        ls
      displayName: Increment build number.
    - script: |
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin:$(FlutterToolPath)/../.pub-cache/bin/
        flutter build ios
      displayName: Build Android & iOS App.
    - task: FlutterTest@0
      inputs:
        projectDirectory: '.'
      displayName: Run Unit Tests.
    - script: |
        git config --global user.email "tk@hinterlandsupply.co"
        git config --global user.name "Azure DevOps CI"
        git add pubspec.yaml
        git commit -m "Updated Automated Build Number [skip ci]"
        git pull origin master --rebase
        git push https://$USERNAME:$PASSWORD@github.com/hinterlandsupplyco/JaMa.git HEAD:master
      displayName: Push updated pubspec
