variables:
  projectDirectory: jama

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

jobs:
  - job: Android
    steps:
    - task: FlutterInstall@0
    - script: |
        echo $(FlutterToolPath)
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin:$(FlutterToolPath)/../.pub-cache/bin/
        echo $PATH
        flutter pub global activate pubspec_version
        cd $(projectDirectory)
        pubver bump build
      displayName: Install pubver tool.
    - script: |
        git add $(projectDirectory)/pubspec.yaml
        git commit -M "Updated Automated Build Number [skip ci]"
        git pull origin master --rebase
        git push origin HEAD:master
      displayName: Push Changes.
  
