trigger:
- master

pool:
  vmImage: 'macOS-10.13'

jobs:
  - job: Android
    steps:
    - task: FlutterInstall@0
    - script: |
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)cache/dart-sdk/bin
        flutter pub global activate pubspec_version
      displayName: Install pubver tool.
  
