trigger:
- master

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Build_And_Test_JaMa
    steps:
    - task: DownloadSecureFile@1
      name: iosApiConstants
      inputs:
        secureFile: 'ApiConstants.swift'
      displayName: Download API Constants
    - script: |
        pwd
        echo $(iosApiConstants.secureFilePath)
        cp $(iosApiConstants.secureFilePath) ios/Runner/
      displayName: Copy API Constants Files
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'Hsco_cert.p12'
        certPwd: '$(privateKeyPassword)'
      displayName: Installing iOS Dev Certificate
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'HSCO.mobileprovision'
      displayName: Installing iOS Dev Mobile Provisioning Profile
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'HSCO-Distribution.p12'
        certPwd: '$(privateKeyPassword)'
      displayName: Installing iOS Dist Certificate
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'HSCOjamadistribution.mobileprovision'
      displayName: Installing iOS Dist Mobile Provisioning Profile
    - task: FlutterInstall@0
    - script: |
        echo $(FlutterToolPath)
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin:$(FlutterToolPath)/../.pub-cache/bin/
        echo $PATH
        flutter pub global activate pubspec_version
        [[ `pubver get` =~ ^[0-9]+.[0,1].0$ ]] && echo "It's a release, don't bump." || pubver bump patch
        pubver set `pubver get`+$(Build.BuildNumber)
      displayName: Increment build number.
    - script: |
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin:$(FlutterToolPath)/../.pub-cache/bin/
        flutter build ios
      displayName: Build Android & iOS App.
    - task: FlutterTest@0
      inputs:
        projectDirectory: '.'
      displayName: Run Unit Tests.
    - script: /usr/bin/xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -archivePath build/ios/iphoneos/JamaRelease.xcarchive -configuration Release archive
      displayName: Archive iOS App
    - script: | 
        /usr/bin/xcodebuild -exportArchive -archivePath build/ios/iphoneos/JamaRelease.xcarchive -exportPath build/ios/iphoneos/ -exportOptionsPlist ios/ExportOptions.plist
        echo 'new alpha.' > build/ios/iphoneos/test_notes.txt
      displayName: Export iOS App
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'build/ios/iphoneos'
        Contents: |
          *.ipa
          test_notes.txt
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: '$(Build.BuildNumber)'
        publishLocation: 'pipeline'
    - script: |
        git config --global user.email "tk@hinterlandsupply.co"
        git config --global user.name "Azure DevOps CI"
        git add pubspec.yaml
        git commit -m "Updated Automated Build Number [skip ci]"
        git pull origin master --rebase
        git push https://$USERNAME:$PASSWORD@github.com/hinterlandsupplyco/JaMa.git HEAD:master
      displayName: Push updated pubspec
