name: jama
version: 0.1.11+20200629.6
description: A new Flutter project.
environment: 
  sdk: '>=2.6.0'
dependencies: 
  kiwi: ^0.2.0
  sembast: ^2.1.2
  path_provider: ^1.5.1
  rxdart: ^0.23.1
  tuple: ^1.0.3
  google_nav_bar: ^1.0.1
  provider: ^4.0.1
  intl: ^0.16.1
  charts_flutter: ^0.8.1
  quiver: ^2.0.5
  slider_button: ^0.4.0
  flutter_xlider: ^3.1.0
  flutter_time_picker_spinner: ^1.0.6
  commons: ^0.7.8+1
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.2
  line_icons: ^0.2.0
  flutter_tableview: ^1.0.1
  duration: ^2.0.8
  flutter_slidable: ^0.5.4
  flutter_widgets: ^0.1.10
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.2.1
  grouped_buttons: ^1.0.4
  icon_shadow: ^1.0.1
  sticky_headers: ^0.1.8+1
  latlong: ^0.6.1
  screenshot: ^0.1.1
  uuid: ^2.0.4
  image: ^2.1.4
  random_color: ^1.0.3
  shared_preferences: ^0.5.6+2
  flutter_sms: 2.0.0+2
  search_widget: ^1.0.2
  popup_menu: ^1.0.5
  toggle_switch: ^0.1.4
  typicons_flutter: ^0.3.1
  flutter_focus_watcher: ^0.0.1
  gradual_stepper: ^1.0.0
  modal_bottom_sheet: ^0.1.6+1
  font_awesome_flutter: ^8.8.1
  calendar_strip: ^1.0.6
  maps_launcher: ^1.2.0
  supercharged: ^1.6.0
  flutter_switch: ^0.1.1
  flutter_cupertino_date_picker: 
    git: https://github.com/rdev-software/flutter-cupertino-date-picker
  flutter: 
    sdk: flutter
  flutter_speed_dial: 
    git: https://github.com/hinterlandsupplyco/flutter_speed_dial.git
  date_picker_timeline: 
    git: https://github.com/hinterlandsupplyco/DatePickerTimelineFlutter.git
dev_dependencies: 
  mockito: ^4.1.1
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - graphics/confetti.png
    - graphics/diamond.png
    - graphics/notebook.png
    - graphics/arrow.png
    - graphics/FakeMap.png
  fonts: 
    - 
      family: Avenir
      fonts: 
        - 
          asset: fonts/Avenir-Heavy.ttf
        - 
          asset: fonts/Avenir-Book.ttf
  uses-material-design: true
